services:
  horizon-router-app:
    build: .
    container_name: horizon-router-app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - API_KEY_SECRET=${API_KEY_SECRET:-horizon-router-api-key}
      - API_KEY_HEADER_NAME=${API_KEY_HEADER_NAME:-X-API-Key}
    ports:
      - "${EXT_PORT_APP:-8000}:${INT_PORT_APP:-8000}"
    restart: unless-stopped
    volumes:
      - horizon_router_logs:/app/logs
    networks:
      - horizon-router-local
    depends_on:
      - horizon-router-mysql
      - horizon-router-redis

  horizon-router-mysql:
    image: mysql:8.0
    container_name: horizon-router-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-horizon-router}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-horizon_router}
      - MYSQL_USER=${MYSQL_USER:-horizon-router}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-horizon-router}
    ports:
      - "${EXT_PORT_MYSQL:-3306}:${INT_PORT_MYSQL:-3306}"
    volumes:
      - horizon_router_mysql_data:/var/lib/mysql
    networks:
      - horizon-router-local
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password

  horizon-router-redis:
    image: redis:7-alpine
    container_name: horizon-router-redis
    restart: unless-stopped
    ports:
      - "${EXT_PORT_REDIS:-6379}:${INT_PORT_REDIS:-6379}"
    networks:
      - horizon-router-local

  horizon-router-celery-worker:
    build: .
    container_name: horizon-router-celery-worker
    depends_on:
      - horizon-router-app
      - horizon-router-redis
      - horizon-router-selenium-chrome
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://horizon-router-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://horizon-router-redis:6379/0
      - USE_REMOTE_SELENIUM=true
      - SELENIUM_HOST=horizon-router-selenium-chrome
      - SELENIUM_PORT=4444
    command: celery -A config.celery.app worker --loglevel=INFO --concurrency=2
    restart: unless-stopped
    volumes:
      - horizon_router_logs:/app/logs
    networks:
      - horizon-router-local

  horizon-router-celery-beat:
    build: .
    container_name: horizon-router-celery-beat
    depends_on:
      - horizon-router-redis
      - horizon-router-mysql
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://horizon-router-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://horizon-router-redis:6379/0
    command: celery -A config.celery.app beat --loglevel=INFO
    restart: unless-stopped
    volumes:
      - horizon_router_logs:/app/logs
    networks:
      - horizon-router-local

  horizon-router-selenium-chrome:
    image: seleniarm/standalone-chromium:latest
    container_name: horizon-router-selenium-chrome
    ports:
      - "${EXT_PORT_SELENIUM:-4444}:${INT_PORT_SELENIUM:-4444}"
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300
      - TZ=UTC
    restart: unless-stopped
    networks:
      - horizon-router-local

networks:
  horizon-router-local:
    driver: bridge

volumes:
  horizon_router_mysql_data:
  horizon_router_logs:
